# CONFIGURATION FILE FOR DECLARING ENVIRONMENT VARIABLES
# Author: Ferch42

# pybox2d and pygame variables

PPM = 20 # Pixel per meters
TARGET_FPS = 60
TIME_STEP = 1.0/TARGET_FPS
SCREEN_WIDTH, SCREEN_HEIGHT = 800, 600
